### PR TITLE
add support for EDN

### PR DESCRIPTION
**Pull request by trevor**
http://edn-format.org

### CODE REVIEW

**Comment by odyssomay** [comment]
I forgot about this...I feel really bad about that. :-1: 

The reason I did not immediately merge it was that I was not really sure _.edn_ is the standard file ending. It makes sense though, I think I'll merge it.

**Comment by trevor** [comment]
Hi @odyssomay, I hope you don't feel _too_ bad about it. :D

Here's supporting evidence for comfort:
https://github.com/Datomic/day-of-datomic/tree/master/resources/day-of-datomic

**Comment by odyssomay** [comment]
Aha, yes that does make me more comfortable. :)

**Comment by odyssomay** [comment]
There we go! Thanks for the contribution. :+1:

**Pull request merged**
